### ISSUE TITLE
优化正则匹配

### ISSUE THREAD

**Issue by sun0225SUN** [zylele/social-readme#2]
这里的正则表达式感觉可以改一下，除了**推荐**字段外，还有像**标签**、**备注**这样的字段，原表达式会匹配错误。

```python
def generate_rating_star(desc) -> str:
    pattern = re.compile(r'<p>推荐: [\s\S]+</p>')
    matches = re.findall(pattern, desc)
    if len(matches) > 0:
        return DOUBAN_RATING[matches[0]]
    return ''
```

![image](https://user-images.githubusercontent.com/79169717/217134112-efa91975-7107-4df5-9f71-ddf1e04e1b76.png)

![image](https://user-images.githubusercontent.com/79169717/217133798-0d27f20e-b3ae-40f9-885a-9f59397ac628.png)

**Comment by zylele** [comment]
@sun0225SUN 嗨，你好，请问这个问题还存在吗？

**Comment by sun0225SUN** [comment]
原来您已经改过来了哇，哈哈哈，打扰了

**Comment by zylele** [comment]
嗯嗯，确实会有bug，感谢提供！
